apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
  namespace: datadog
spec:
  global:
    site: us5.datadoghq.com
    clusterName: auction-site-cluster
    registry: gcr.io/datadoghq
  agent:
    image:
      name: agent
      tag: 7.47.0    # >=7.40.0 for K8s v1.25+, safe choice
  clusterAgent:
    image:
      name: cluster-agent
      tag: 7.47.0    # >=1.18.0, >=7.40.0 for K8s v1.25+
    config:
      orchestratorExplorer:
        enabled: true
  features:
    logCollection:
      enabled: true
    apm:
      enabled: true
