name: Build and Push Docker Images

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  DOCKER_REGISTRY: docker.io
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
        
    - name: Install Skaffold
      run: |
        curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
        sudo install skaffold /usr/local/bin/
        
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies for common package
      run: |
        cd common
        npm ci
        
    - name: Build and push images with Skaffold
      run: |
        # Create a production skaffold config for pushing
        cat > skaffold-prod.yaml << EOF
        apiVersion: skaffold/v2alpha3
        kind: Config
        build:
          artifacts:
            - image: thetharz/auction-website-auth
              context: services/auth
              docker:
                dockerfile: Dockerfile
            - image: thetharz/auction-website-listings
              context: services/listings
              docker:
                dockerfile: Dockerfile
            - image: thetharz/auction-website-bid
              context: services/bid
              docker:
                dockerfile: Dockerfile
            - image: thetharz/auction-website-expiration
              context: services/expiration
              docker:
                dockerfile: Dockerfile
            - image: thetharz/auction-website-profile
              context: services/profile
              docker:
                dockerfile: Dockerfile
            - image: thetharz/auction-website-frontend
              context: services/frontend
              docker:
                dockerfile: Dockerfile
            - image: thetharz/auction-website-email
              context: services/email
              docker:
                dockerfile: Dockerfile
            - image: thetharz/auction-website-payments
              context: services/payments
              docker:
                dockerfile: Dockerfile
          tagPolicy:
            envTemplate:
              template: "{{.GITHUB_SHA}}"
        EOF
        
        # Build and push images
        skaffold build -f skaffold-prod.yaml --push
        
    - name: Tag and push latest
      if: github.ref == 'refs/heads/main'
      run: |
        # Tag and push as latest for main branch
        docker tag thetharz/auction-website-auth:${{ github.sha }} thetharz/auction-website-auth:latest
        docker tag thetharz/auction-website-listings:${{ github.sha }} thetharz/auction-website-listings:latest
        docker tag thetharz/auction-website-bid:${{ github.sha }} thetharz/auction-website-bid:latest
        docker tag thetharz/auction-website-expiration:${{ github.sha }} thetharz/auction-website-expiration:latest
        docker tag thetharz/auction-website-profile:${{ github.sha }} thetharz/auction-website-profile:latest
        docker tag thetharz/auction-website-frontend:${{ github.sha }} thetharz/auction-website-frontend:latest
        docker tag thetharz/auction-website-email:${{ github.sha }} thetharz/auction-website-email:latest
        docker tag thetharz/auction-website-payments:${{ github.sha }} thetharz/auction-website-payments:latest
        
        docker push thetharz/auction-website-auth:latest
        docker push thetharz/auction-website-listings:latest
        docker push thetharz/auction-website-bid:latest
        docker push thetharz/auction-website-expiration:latest
        docker push thetharz/auction-website-profile:latest
        docker push thetharz/auction-website-frontend:latest
        docker push thetharz/auction-website-email:latest
        docker push thetharz/auction-website-payments:latest
